In [1]:
import pandas as pd
import geopandas as gpd

open pandas read csv

In [10]:
texas = pd.read_csv('../Maps/Aa5872-5934.csv')
texas.head(16)

,Year,Area_Aa5872_SquareMiles,PopulationDensity_Aa5873_PersonsPerSquareMile,Population_Total_Aa5874_Number,Population_Race_White_Aa5875_Number,Population_Race_Nonwhite_Aa5876_Number,Population_Race_Black_Aa5877_Number,Population_Race_OtherNonwhite_Aa5878_Number,Population_Residence_Urban_Aa5879_Number,Population_Residence_Rural_Aa5880_Number,Population_Nativity_Native-born_Aa5881_Number,Population_Nativity_Foreign-born_Aa5882_Number
0,1850,262398,0.81,212592,154034,58558,58558,NaN,7665,204927,194911,17681
1,1860,262398,2.30,604215,420891,183324,182921,403.0,26615,577600,560793,43422
2,1870,262398,3.12,818579,564700,253879,253475,404.0,54521,764058,756168,62411
3,1880,262398,6.07,1591749,1197237,394512,393384,1128.0,146795,1444954,1477133,114616
4,1890,262398,8.52,2235527,1745935,489588,488171,1417.0,349511,1886016,2082567,152956
5,1900,262398,11.62,3048710,2426669,622041,620722,1319.0,520759,2527951,2869353,179357
6,1910,262398,14.85,3896542,3204848,691694,690049,1645.0,938104,2958438,3654604,241938
7,1920,262398,17.77,4663228,3918165,745063,741694,3369.0,1512689,3150539,4299396,363832
8,1930,262398,22.20,5824715,4967172,857543,854964,2579.0,2389348,3435367,5462428,362257
9,1940,263644,24.33,6414824,5487545,927279,924391,2888.0,2911389,3503435,6179296,235528
10,1950,263513,29.26,7711194,6726534,984660,977458,7202.0,4838060,2873134,7408150,277515
11,1960,262970,36.43,9579677,8374831,1204846,1187125,17721.0,7187470,2392207,9282717,298791
12,1970,262134,42.71,11196730,9717128,1479602,1399005,80597.0,8922211,2274519,10885644,309772
13,1980,262017,54.31,14229191,11198441,3030750,1710175,1320575.0,11333017,2896174,13372978,856213
14,1990,261914,64.86,16986510,12774762,4211748,2021632,2190116.0,13634517,3351993,15462074,1524436